branches:
  only:
  - master
  - "/^v[0-9]+(\\.[0-9]+)*(\\.[0-9]+)*\\S*/"
dist: bionic
language: python
matrix:
  include:
  - python: 3.6
    env:
    - TRAVIS_PYTHON_VERSION=3.6
    - CONDA_PY=36
    - CONDA_NPY=116
  - python: 3.7
    env:
    - TRAVIS_PYTHON_VERSION=3.7
    - CONDA_PY=37
    - CONDA_NPY=116
  - python: 3.8
    env:
    - TRAVIS_PYTHON_VERSION=3.8
    - CONDA_PY=38
    - CONDA_NPY=117
  - python: 3.9
    env:
    - TRAVIS_PYTHON_VERSION=3.9
    - CONDA_PY=39
    - CONDA_NPY=119
    - CREATE_DOCS=1

env:
  global:
  - ANACONDA_USERNAME=MaxBo
  - TWINE_USERNAME=MaxBo
  - TWINE_REPOSITORY=pypi
  - TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
  - secure: yKn/QHVBYoESrqaB0ZdHgO1qds01TtnTj+F4zjGXGSDOuhG0mzlpu9oY0CC6vgwbq2YN8ypbSZ0ZiI8fL9nVcerhnJcHe80znpioTkjnIUapM7MWHmkDV2w953Ad4e1NiT+TEXP8yqK1euY+ZlcpuR4gkAYAszCMhgwWPCw3vqnPViBYSD3SMSrdjAPp7mGSweQEnWFrI/Z+uWGKCbLYlAQRbpJCeioG8vzpnmli8EGL16wj92i4yy4lcGZZTXaJFCZt1OBxdsXRPom+7gwnOnWEwaqLw0kCLFMiTRX5pZWhOp0AKGXrwegz81qaeeEbCPdpuDsLCUksmpoE0Wghogl/Q3ouCMhK5id7RXk+CbTbRxP8mvIhaZPtX3I6OVMQLbqvIDgOZj1dMQ8oFhck9sSLh2z+oxM/BesshuvJM0fQk5dvGAiObUsgevD2pCvJLGarCcmITlSXcyl08K+lW+vBB9Vzl9YkWchvCPNDMgVAjbMWP93D98KivsKzGwnjWof8GFJ30Yp3PhklEbqVAg6aooT5QyhQrEFbzmUbJ5uTFHsx6J+xsjrhE0i+FI6kVoHw8c0Jx/QleN+KBSxjXYN0YB907Ns+k1T9Ajd9waXn2iDPLatUvBvmZ7mnu6ngRX3LvVJbiGqiHckU6LxvNLO3SgJU9XL1Wb/cmsCsmXk=
  - secure: XSywMGCavKPO937o8JWSxlMbuzjUJ9ygpep4ybIaZ6knF2X2uYkT5FAm8VNoRS1/lmEKlaTaorwPHx0KGNcsQMor2gi+qyoJ3ODVranzLhAL3/9pBtWl9B4kbfC0gGitFS8e/X5n0SIuWI3xgjFdkotPnGAeorF+9OhiTQ2Xr4UdURyD5UJUh98SK//wtlXw/gflK7oHDxxumiecPY47wtn1v3vZTL3by27cJr8X8r/J6qmOS3qW2hEG61Rccjj5TSh4EvWWfoDGm7x2vojmPFF6C3yt8e/Y9X4R2W1N1Ni9DEwKA9z37nXtxJRdZG1tIra2PrxgrLNf3v1nMWMMC7gTGLV7Dly+g6+udmEeJbuWLwTrP+HNhlQvTjWVbNhfxsdiyYejTjcVVRUb/b1HuXVQworIoMfiPxFNzUtl9LoRKDq91ZhrfMvCHM9DcSN7YvkX/sgHuPHOTUsjWS3MYBkPHzkjPzYUPfs7tAZnqIMSVUT0npFjZBuTIL/mSmRgO1MRMaLYXvReedEdOh2dKP1y3NxEWiCEIWomEACLTZqjmSDjeoeCPAM8CJZNnhfkRLAE52eTPWZKmzhnk1h8j0IKJlLoE3TasDF6yVu15k2XkpY/szmJ0eS9/m7bsC7bHJ6VG9trDEGJT1NnCXXaR8WBObpvt6+kKrkpzMxAu8E=
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda install conda-build conda-verify anaconda-client
- conda info -a
- conda config --set show_channel_urls true
- conda config --remove channels defaults
- conda config --add channels defaults
- conda config --add channels conda-forge
- conda config --add channels MaxBo
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest-cov
- export TMPDIR=`dirname $(mktemp -u -t tmp.XXXXXXXXXX)`
- export CONDA_BLD_PATH=$TMPDIR
- conda build cythoninstallhelpers/conda.recipe
- conda install -y --use-local cythoninstallhelpers
- source activate test-environment
- export PATH=$HOME/.local/bin:$PATH

script:
- conda info -a
- conda build cythoninstallhelpers/conda.recipe
- conda install -y --use-local cythoninstallhelpers
- conda build cythonarrays/conda.recipe
- conda build matrixconverters/conda.recipe
- if [ "${CREATE_DOCS}" = "1" ]; then
    conda install -y --use-local cythonarrays matrixconverters;
    pip install --user sphinx sphinxcontrib-napoleon sphinx-autodoc-typehints m2r2 travis-sphinx;
    sphinx-apidoc -f --separate -o docs_rst/cythoninstallhelpers cythoninstallhelpers/src/cythoninstallhelpers;
    sphinx-apidoc -f --separate -o docs_rst/cythonarrays cythonarrays/src/cythonarrays;
    sphinx-apidoc -f --separate -o docs_rst/matrixconverters matrixconverters/src/matrixconverters;
    travis-sphinx build --source docs_rst --nowarn;
  fi
after_success:
- if [ "${CREATE_DOCS}" = "1" ]; then travis-sphinx deploy; fi
- |-
  if [ "${TRAVIS_TAG}" ]; then
    anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/cythoninstallhelpers-*.tar.bz2;
    anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/cythonarrays-*.tar.bz2;
    anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/matrixconverters-*.tar.bz2;
    conda install -y twine;
    pip install readme_renderer;
    cd $TRAVIS_BUILD_DIR/cythoninstallhelpers;
    python setup.py sdist bdist_wheel;
    twine upload --skip-existing dist/*;
    conda install -y cythoninstallhelpers;
    cd $TRAVIS_BUILD_DIR/cythonarrays;
    python setup.py sdist bdist_wheel;
    twine upload --skip-existing dist/*;
    conda install -y cythonarrays;
    cd $TRAVIS_BUILD_DIR/matrixconverters;
    python setup.py sdist bdist_wheel;
    twine upload --skip-existing dist/*;
  fi
