# safelist
#branches:
#  only:
#  - master

language: python

matrix:
    include:
        - python: 3.5
          env:
            - TRAVIS_PYTHON_VERSION=3.5
            - CONDA_PY=35
            - CONDA_NPY=114
        - python: 3.6
          env:
            - TRAVIS_PYTHON_VERSION=3.6
            - CONDA_PY=36
            - CONDA_NPY=114
            - CREATE_DOCS=1

env:
  global:
    - ANACONDA_USERNAME=MaxBo
    # ANACONDA_TOKEN
    - secure: kWIJPammSoqLZVSeAaDeG9hEptHX3uXw1nnMepALXvLEd2ZKpyeieym51nJXLK8vZtfgJ5lNI7gUF2dNldj5xdiYNCGZqvIQBU0Nle9DeepRcucOMmsDZPHkODyJ0dRn3WTtJF+owaj+LFd9VbeBDg2vcj5LOIb53kTym0uXefZDT6fnkBG2BUh2Wyp81H9xvMqyM2J8FfPMLdgjOcaP7M6OH0a6BOLoPdUMvoqjmlnd1s7CpFZj+tBImHkI9GaxZRJq5fySQXTXjuEOTqfMMfyk4yGKeZ+svAbhcoiuw6jMdNTwGpOPPV+c35HTEIJ23gNc08FQ5lGNFo05lf5ex4D8Ri7F7JOkRkn58W6vqjWb2mjhLXV+Md9dDU0UkZd78F+28uBJnVqJ2ll3wdDznwQ7i1U9ZH2As90YveIrYJv0gD7kqXu4BBwmXAZAytSQ/NFP2GsNEjIrk6+wtR/H2XVncpvvgLHCtz2pvUxh1Gq0bqbj3AZPewKUKKEJ/Ilct3KHMlkfQNE0j8OE4RrvHwk1bIvnUnWois6vvuouJ2KrTKX4Y+o8VJOFSS5yMCP38YzBH0ID6syWLdDaf7rSOzg6Z+eR1qE0E98Z6XmH+m3mE1n+fyAu9uxMMd8uGkPcDUIRI0W11q+Xf+NYz2ID8lu2fb8j/IKKYDAubQyIGeQ=
    - TWINE_USERNAME=MaxBo
    - TWINE_REPOSITORY=pypi
    - TWINE_REPOSITORY_URL=https://pypi.python.org/pypi/
    # TWINE_PASSWORD
    - secure: jAWjWb+WzxQ4ZCwYWTMJ5H9JcbhUDXYp/j1A52AT9T4E2Ta+sBey8gCskZIPPrPs4yxgcghlaap69y7c/LEk5/nxlfqqT8SGn5FSIztV0Wf8eIcPFLI7jKfo5oX1Suwar21T/FahDI/uNmmIZBQejXzL8IfmmJ3ayMqRLxKQPEn1nhZF8bDyVH+O5TefoE4W484dx00IjDGNbDD8EjfIaLMLQkfbMMBOAIiK8lwxFXfaaDuOlrWAof1iAtOiLuPNLVrQ6jLZzKKuOZnM62mjnaLGxmdAYfX7x61qZQIlrjrLfA008O11M5BkddmglPJ51HNzWGQZ34j8Pc/QRd8LrIoufDpTDbDzzkvy7QYZTjoBNAG2hlgfnRd2QSVALr7wpeFugH6vsk6jntCvIMfgLoSslbgC2ZpXIjX96JKhw4W1BE1vXHw5oUBtkKrdNuZksHo5Yvj8vCAnxOwySBr/0aEYFaNWhZrdpVCveBsvMq4O0VeTKyMpxAZa/eCfe0IH/Jwvra/p0mEd6N5xA5o1J+/z7kwF2yJYUNoHUJNNTWkvZdfW0abpRJ4qMaMLVQHh/uooNozflhmv4+j8DT8Yyrep4mnVpafG7O59sgycEi0gxI4xS5kDl6R51SxwF8Nnu1lZquZAYar/auN93YZdRHTEbhtWOvt1y/98+G9z91A=

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  - conda install anaconda-client
  # Useful for debugging any issues with conda
  - conda info -a

  - conda config --set show_channel_urls true
  - conda config --remove channels defaults
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels MaxBo

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - export TMPDIR=`dirname $(mktemp -u -t tmp.XXXXXXXXXX)`
  - export CONDA_BLD_PATH=$TMPDIR
  - conda build cythoninstallhelpers/conda.recipe --no-anaconda-upload
  - conda install -y --use-local -n root cythoninstallhelpers
  
  - source activate test-environment
  - conda install -y sphinx numpydoc
  - pip install --user travis-sphinx
  - export PATH=$HOME/.local/bin:$PATH
  - conda install pytest-cov

script:
  # Your test script goes here
  - conda info -a
  - conda build cythoninstallhelpers/conda.recipe
  - conda install -y --use-local cythoninstallhelpers
  - conda build cythonarrays/conda.recipe
  - conda build matrixconverters/conda.recipe

  # build documentation
  - if [ "${CREATE_DOCS}" = "1" ]; then
      conda install -y --use-local cythonarrays matrixconverters;
      sphinx-apidoc -f --separate -o docs_rst/cythoninstallhelpers cythoninstallhelpers/src/cythoninstallhelpers;
      sphinx-apidoc -f --separate -o docs_rst/cythonarrays cythonarrays/src/cythonarrays;
      sphinx-apidoc -f --separate -o docs_rst/matrixconverters matrixconverters/src/matrixconverters;
      travis-sphinx build --source docs_rst --nowarn;
    fi

after_success:
  - if [ "${CREATE_DOCS}" = "1" ]; then travis-sphinx deploy; fi

  - if [ "${TRAVIS_TAG}" ]; then
      anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/cythoninstallhelpers-*.tar.bz2;
      anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/cythonarrays-*.tar.bz2;
      anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/matrixconverters-*.tar.bz2;

      conda install -y twine;
      cd $TRAVIS_BUILD_DIR/cythoninstallhelpers;
      python setup.py sdist bdist_wheel;
      twine upload --skip-existing dist/*;
      conda install -y cythoninstallhelpers;
      cd $TRAVIS_BUILD_DIR/cythonarrays;
      python setup.py sdist bdist_wheel;
      twine upload --skip-existing dist/*;
      conda install -y cythonarrays;
      cd $TRAVIS_BUILD_DIR/matrixconverters;
      python setup.py sdist bdist_wheel;
      twine upload --skip-existing dist/*;

    fi
