# safelist
#branches:
#  only:
#  - master

language: python

matrix:
    include:
        - python: 3.5
          env:
            - TRAVIS_PYTHON_VERSION=3.5
            - CONDA_PY=35
            - CONDA_NPY=114
        - python: 3.6
          env:
            - TRAVIS_PYTHON_VERSION=3.6
            - CONDA_PY=36
            - CONDA_NPY=114
            - CREATE_DOCS=1

env:
  global:
    - secure: wCwWAKo8LJJtMHEaIOQ3P908VQ6EKnIQrDSd/bSmu8npc4x7Mxqmans40z75D3NR2TuTdCA9xXmqdQG96RKqOQlDzho8w4vg0VQUHKgJ9Qsqu+u5K1jm/PyrQYXSQIKNSGU+iEunwWTJiUhV8bVpjfK7QJtBwImZW6HayN8Qt9UAY242nBP3VjsU/RFc2HR1e5yfDA5IGokxuJeDG2xUEOcIvzx2Dv0MwUrLQa7ntb1t6fj0wv6/CuTdX1dQ90OYrT2qqtij07J38W2WWUYmSs1+xc3KgWZ6UukqcJv9wGmW/oiCthAF96ASHYUcOaNWs3VVL6NCfkqY2qpeBON2nH470Lu67cJZ32dXGMFLYiyaBiqE7092NIUX2PGFD5yTXWiLVCp9Kys+0lkDLaD4xy09/Op36xZlktZmzgZEgmz4uGZF3NAGsnOpmlV2KvQi1VIMN6dQ1Mkn4kIgFG+U4swXQv+zUZRZC3ohp15bykEDDAlYr154wonrRWWgA1N9HcPNOHb1rkLp2YYA9uqODYVnT09xFIcECnPo9qyryxZY0zdJX/IZZjH3FIILu0dEtVyDK1ItepkTcdkm5I0zN/VckNRrpaLnalBeJqdRzvfNij3hnVR7qm0zUPqYR7IXuJ58ds/SPs4Qq8OpfAGQcx/ZFAk4kS4/WirWVeQC3wY=
    - secure: HHM2bkK3hY/4fW2n61ITSS/bT7bOY+rcPZiwAbB14oql2wONi5xoaRPa3Q9eyEpj9uT1LhU1jAyXEXyjSLRCVSMY0TkpdrxtkhpWoD5zaJXJVgyiK2DmJh0kfjCT35PIsGT6IV/H5mPxJBogytzcTvYIa12SZpmH+fvo67TrXGohu83iNjNt46EcvFPECozNTqF7FW17VIm8fBJUJwUPW4l8NQGAxcXi+q8ePTZYijCDmA4wqgi52HSj0bdNtTDsKCa4DfbD+AlS/vZ7rXFhOlGnQXq88K/FhdBObqLeOrOvtPoWZ7cwRFpK1ShUeszZA605qIWgCL7y4bQL3cCqfuLECD60PXaM16iHvXxKtTAVPxZUKKxWY7QRZ9TgntrwqsZH4Vk5ltg5S7mhgS2EgXUh7CXT2hdPNzHYI6GVPxrOdcQrKOx2XmHiHIOdBuGGga212p2i8Apu5g7iujr/BYUDiSdbG/6rd1QlxeHY3UQcYJBkY9B5Qhx3HDK9gOYaZprmmear9VpsxO1V4hHoNaalhqPgbZYipr4CwT3d1EUTxOabovQkWK6t0SOKYR2dwD9X23A8hd3R8fmokicqobFlsLlU9fCb94AQt3I3WVni4es6p4trKUfZTXWAv20i/Rsh+bhAoK5bjzeWfPNzctOCcBdWj3uWwJD0c5QdWSo=
    # Travis-remote-shell
    #- secure: J7OQyUjKPOfo1PDK5/s5QDgbV9mN8js3jhKBtg7M4R+mXarThEacAE8Rov4rzKxPABLwMaoEAPvVggPXgESG7RbN+gsOA7ZCv8vFubvWrX9o/bp9ahK9iAvXuumwW2D5MN9ehMLY2rhZcLNYeip6DuvehrguLp2XDFgmjXL6rDCYJz+7XlbuqcjCwjj/d+4bel9wvrijQtRBzUn3qgJY2kDgmX3PUz7L3cWGPl9WmZ00amtCDbU3Gku5KsqKIP4MFIEFB9eH6ep+DQdzgLTtOzPzr0rP3P+ek0UQKePtcYXqbv5gjBnZAREVhmD7Aby2aN9HTXD9SQs1er5ySrmla3xEaRkQ3uWbxKHzHYlFFuNxZRukWLIbfBXLPTbM37fF6IJvNz2v64YDFRijUsOpMZbrksPgA9UYymf6SJ9EX/5LRiVPiSjIVeReaIgWG7SSrXCE+f+muzeOdQqCl1qRezKuEQFGDchsU4XPNWB+7h8c+CfXEPSjobrvROwN/qtw3uCyxiuNGeVtK3EktsbJLafDt45ZNn91KD7y85Md5tOSUwVGgJm3XSkeyq4FbPURTp4+R7+Gp1nS0uusiSrPLUR6QV0x0juliY+imGVCKIlJXg175sBMAU8K5VpQhMxmhYRa6Zp1uAT4v+UY/GDrVgDa57sOF2MurWWhjLuS6HI=

#before_install:
#  - eval "$(curl -sL https://raw.github.com/sysgears/travis-remote-shell/master/run.sh)"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  - conda install anaconda-client
  # Useful for debugging any issues with conda
  - conda info -a

  - conda config --set show_channel_urls true
  - conda config --remove channels defaults
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels MaxBo

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - export TMPDIR=`dirname $(mktemp -u -t tmp.XXXXXXXXXX)`
  - export CONDA_BLD_PATH=$TMPDIR
  - conda install -y sphinx numpydoc
  - pip install --user travis-sphinx
  - conda install pytest-cov

script:
  # Your test script goes here
  - conda info -a
  - conda build cythoninstallhelpers/conda.recipe --user MaxBo --token $ANACONDA_TOKEN
  - conda install -y --use-local -n root cythoninstallhelpers
  - conda install -y --use-local cythoninstallhelpers
  - conda build cythonarrays/conda.recipe --user MaxBo --token $ANACONDA_TOKEN
  - conda build matrixconverters/conda.recipe --user MaxBo --token $ANACONDA_TOKEN

  # build documentation
  - if [ "${CREATE_DOCS}" = "1" ]; then
      conda install -y --use-local cythonarrays matrixconverters;
      sphinx-apidoc -f --separate -o docs_rst/cythoninstallhelpers cythoninstallhelpers/src/cythoninstallhelpers;
      sphinx-apidoc -f --separate -o docs_rst/cythonarrays cythonarrays/src/cythonarrays;
      sphinx-apidoc -f --separate -o docs_rst/matrixconverters matrixconverters/src/matrixconverters;
      travis-sphinx --source docs_rst --nowarn build;
    fi

after_success:
  - if [ "${CREATE_DOCS}" = "1" ]; then travis-sphinx deploy; fi

  - if [ "${TRAVIS_TAG}" ]; then
      conda install -y twine;
      cd $TRAVIS_BUILD_DIR/cythoninstallhelpers;
      python setup.py sdist;
      twine upload --skip-existing dist/*;
      conda install -y cythoninstallhelpers;
      cd $TRAVIS_BUILD_DIR/cythonarrays;
      python setup.py sdist;
      twine upload --skip-existing dist/*;
      conda install -y cythonarrays;
      cd $TRAVIS_BUILD_DIR/matrixconverters;
      python setup.py sdist;
      twine upload --skip-existing dist/*;
    fi

