{% set version_str = load_file_regex(load_file='src/matrixconverters/_version.py', regex_pattern='^[_]{0,2}version[_]{0,2}\\s*=\\s*[\'\\"]([^\'\\"]*)[\'\\"]') %}

package:
  name: matrixconverters
  version: {{ version_str[1] }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools>=61.0

  run:
    - python
    - numpy>=1.12
    - xarray
    - h5netcdf
    - pytest-cov

test:
  requires:
    - pytest-cov
  commands:
    - py.test --pyargs matrixconverters

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'cython cdef-class to facilitate numpy-arrays as attributes..'
