{% set data = load_setup_py_data() %}

package:
  name: matrixconverters
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - cythoninstallhelpers
    - numpy>=1.12
    - xarray
    - netcdf4<=1.6.2

  run:
    - python
    - cythoninstallhelpers
    - numpy>=1.12
    - xarray
    - netcdf4<=1.6.2
    - pytest-cov

test:
  requires:
    - pytest-cov
  commands:
    - py.test --pyargs matrixconverters

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'cython cdef-class to facilitate numpy-arrays as attributes..'
