{% set data = load_setup_py_data() %}

package:
  name: matrixconverters
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - xarray
    - cythoninstallhelpers
    - netcdf4
    - pytest
    - pytest-runner
    - pytest-cov
  run:
    - python
    - setuptools
    - numpy
    - xarray
    - netcdf4
    - cythoninstallhelpers

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
  commands:
    - py.test --junitxml={{ environ["TMPDIR"] }}/junit_matrixconverters.xml --cov=..\src --cov-report xml --pyargs matrixconverters

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'cython cdef-class to facilitate numpy-arrays as attributes..'
