{% set version = "dev" %}

package:
  name: cythoninstallhelpers
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - cython

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'helper for cython installation..'
