{% set data = load_setup_py_data() %}

package:
  name: cythoninstallhelpers
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools>=41
    - numpy>=1.12
    - cython

  run:
    - python
    - setuptools>=41
    - numpy>=1.12
    - pytest
    - cython

test:
  requires:
    - pytest

  commands:
    - py.test --pyargs cythoninstallhelpers

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'helper for cython installation..'
