{% set version_str = load_file_regex(load_file='src/cythoninstallhelpers/_version.py', regex_pattern='^[_]{0,2}version[_]{0,2}\\s*=\\s*[\'\\"]([^\'\\"]*)[\'\\"]') %}

package:
  name: cythoninstallhelpers
  version: {{ version_str[1] }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools>=61

  run:
    - python
    - setuptools>=61
    - numpy>=1.12
    - cython

test:
  requires:
    - pytest-cov

  commands:
    - py.test --pyargs cythoninstallhelpers

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'helper for cython installation..'
