{% set data = load_setup_py_data() %}

package:
  name: cythonarrays
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools>=41
    - cython
    - numpy>=1.12
    - xarray
    - netcdf4
    - cythoninstallhelpers

  run:
    - python
    - setuptools>=41
    - cython
    - numpy>=1.12
    - xarray
    - netcdf4
    - cythoninstallhelpers
    - pytest

test:
  requires:
    - pytest
  commands:
    - py.test --junitxml={{ environ["TMPDIR"] }}/junit_cythonarrays.xml --pyargs cythonarrays

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'cython cdef-class to facilitate numpy-arrays as attributes..'
