{% set version_str = load_file_regex(load_file='src/cythonarrays/_version.py', regex_pattern='^[_]{0,2}version[_]{0,2}\\s*=\\s*[\'\\"]([^\'\\"]*)[\'\\"]') %}

package:
  name: cythonarrays
  version: {{ version_str[1] }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools>=61
    - cython
    - numpy>=1.12

  run:
    - python
    - cython
    - numpy>=1.12
    - xarray
    - h5netcdf>=1.16

test:
  requires:
    - pytest-cov
  commands:
    - pytest --pyargs cythonarrays

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'cython cdef-class to facilitate numpy-arrays as attributes..'
