{% set data = load_setup_py_data() %}

package:
  name: cythonarrays
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools
    - cython >= 0.27.1
    - numpy
    - xarray
    - cythoninstallhelpers
    - pytest
    - pytest-runner
  run:
    - python
    - setuptools
    - numpy
    - xarray
    - cythoninstallhelpers
    - pytest
    - pytest-runner
test:
  requires:
    - pytest
    - pytest-runner
  commands:
    - py.test --junitxml={{ environ["TMPDIR"] }}/junit_cythonarrays.xml --pyargs cythonarrays

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'cython cdef-class to facilitate numpy-arrays as attributes..'
