{% set version = "dev" %}

package:
  name: cythonarrays
  version: {{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - xarray
    - pip:
      - cythoninstallhelpers

  run:
    - python
    - setuptools
    - numpy
    - xarray

test:
  requires:
    - pytest
  commands:
    - py.test

about:
  home: https://maxbo.github.io/cythonarrays
  license: GPL2
summary: 'cython cdef-class to facilitate numpy-arrays as attributes..'
