name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Setup base conda for Python 3.7
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.7
        conda-channels: MaxBo, conda-forge, defaults

    - name: Install dependencies and set channels
      run: |
        conda install conda-build conda-verify anaconda-client
        conda info -a
    - name: Create test environment for conda ${{ matrix.python-version }}
      run: |
        conda create -q -n test-environment python=${{ matrix.python-version }} pytest-cov
        cd cythoninstallhelpers
        pip install -r requirements.txt
        pip install .
        cd ..
        source activate test-environment
        export PATH=$HOME/.local/bin:$PATH
    - name: Build and test
      run: |
        export TMPDIR=${{ env.RUNNER_TEMP }}
        export CONDA_BLD_PATH=$TMPDIR
        conda info -a
        conda build cythoninstallhelpers/conda.recipe
        conda install -y --use-local cythoninstallhelpers
        conda build cythonarrays/conda.recipe
        conda build matrixconverters/conda.recipe
        source activate test-environment
        export PATH=$HOME/.local/bin:$PATH
    - name: Create Docs
      if: ${{ matrix.python-version == '3.10' }}
      run: |
        conda install -y --use-local cythonarrays matrixconverters
        pip install --user sphinx sphinxcontrib-napoleon sphinx-autodoc-typehints m2r2 travis-sphinx
        sphinx-apidoc -f --separate -o docs_rst/cythoninstallhelpers cythoninstallhelpers/src/cythoninstallhelpers
        sphinx-apidoc -f --separate -o docs_rst/cythonarrays cythonarrays/src/cythonarrays
        sphinx-apidoc -f --separate -o docs_rst/matrixconverters matrixconverters/src/matrixconverters
        travis-sphinx build --source docs_rst --nowarn
        travis-sphinx deploy
    - name: Upload files
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_GITHUBACTION_TOKEN }}
        ANACONDA_USERNAME: MaxBo
        TWINE_REPOSITORY: pypi
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
        TWINE_USERNAME: MaxBo
        TWINE_PASSWORD: ${{ secrets.TWINE_GITHUBACTION_TOKEN }}
      if: ${{ github.ref_type == 'TAG' }}
      run: |
        anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/cythoninstallhelpers-*.tar.bz2
        anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/cythonarrays-*.tar.bz2
        anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/matrixconverters-*.tar.bz2
        conda install -y twine
        pip install readme_renderer
        cd cythoninstallhelpers
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*
        conda install -y cythoninstallhelpers
        cd ../cythonarrays
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*
        conda install -y cythonarrays
        cd ../matrixconverters
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*